### ISSUE TITLE
`QuantumCell.call` method - documentation and implementation do not match

### ISSUE THREAD

**Issue by rajibchakravorty** [eperrier/QDataSet#1]
`QuantumCell`'s `call` method has following implementation
```
def call(self, inputs, states):        
        """
        This method must be defined for any custom layer, it is where the calculations are done.   
        
        inputs: The tensor representing the input to the layer. This is passed automatically by tensorflow.
        states: The tensor representing the state of the cell. This is passed automatically by tensorflow.
        """         
        
        previous_output = states[0] 
        
        # evaluate -i*H*delta_T
        Hamiltonian = inputs * self.delta_T
        
        #evaluate U = expm(-i*H*delta_T)
        U = tf.linalg.expm( Hamiltonian )
        
        # accuamalte U to to the rest of the propagators
        new_output  = tf.matmul(U, previous_output)    
        
        return new_output, [new_output]
```

`Hamiltonian` calculation is apparently missing the constant of `-i` (or the documentation in the line above is incorrect).

Can you please confirm?

**Comment by eperrier** [comment]
Thanks for the comment. The imaginary unit (-i) is already included in the definition of self.delta_t in the constructor of the class. Instead of having to undertake multiplications -1j * H * delta t, every time (this is one of the most called functions in the while code), we just have two multiplications H*delta t, where delta t is redefined once at the beginning before any calculations to include the imaginary number

**Comment by rajibchakravorty** [comment]
Completely missed that. Many thanks.
